.PHONY: lint dev lint-check unit-tests coverage html-cov audit build

lint:
	poetry run black .
	poetry run ruff check --fix .

dev: lint
	poetry run pyright .

lint-check:
	poetry run black --check .
	poetry run ruff check .
	poetry run pyright .
	poetry run interrogate {{ cookiecutter.package_name }}/ --verbose

unit-tests:
	poetry run python -m pytest -v

coverage:
	poetry run coverage run --branch --source={{ cookiecutter.package_name }} -m pytest -m "not skip_coverage"
	poetry run coverage report --fail-under=90
	poetry run coverage lcov

html-cov: coverage
	poetry run coverage html

audit:
	poetry audit --ignore-package=py

build:
	poetry build
